[2023-05-11T10:56:02.341+0000] {logging_mixin.py:149} INFO - Changing /opt/***/logs/dag_id=tiktok_processing/run_id=scheduled__2023-05-10T00:00:00+00:00/task_id=file_sensor permission to 509
[2023-05-11T10:56:02.767+0000] {logging_mixin.py:149} INFO - Changing /opt/***/logs/dag_id=tiktok_processing/run_id=scheduled__2023-05-10T00:00:00+00:00/task_id=file_sensor permission to 509
[2023-05-11T10:56:03.257+0000] {logging_mixin.py:149} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/sqlalchemy.py:124 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2023-05-11T10:56:03.330+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tiktok_processing.file_sensor scheduled__2023-05-10T00:00:00+00:00 [queued]>
[2023-05-11T10:56:03.377+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tiktok_processing.file_sensor scheduled__2023-05-10T00:00:00+00:00 [queued]>
[2023-05-11T10:56:03.396+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 1
[2023-05-11T10:56:03.551+0000] {taskinstance.py:1350} INFO - Executing <Task(FileSensor): file_sensor> on 2023-05-10 00:00:00+00:00
[2023-05-11T10:56:07.855+0000] {standard_task_runner.py:57} INFO - Started process 1065 to run task
[2023-05-11T10:56:09.299+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'tiktok_processing', 'file_sensor', 'scheduled__2023-05-10T00:00:00+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/task_7_1.py', '--cfg-path', '/tmp/tmpk9ssdiun']
[2023-05-11T10:56:09.344+0000] {standard_task_runner.py:85} INFO - Job 9: Subtask file_sensor
[2023-05-11T10:56:18.566+0000] {logging_mixin.py:149} WARNING - /home/***/.local/lib/python3.7/site-packages/***/settings.py:188 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2023-05-11T10:56:27.879+0000] {logging_mixin.py:149} INFO - Changing /opt/***/logs/dag_id=tiktok_processing/run_id=scheduled__2023-05-10T00:00:00+00:00/task_id=file_sensor permission to 509
[2023-05-11T10:56:27.901+0000] {task_command.py:410} INFO - Running <TaskInstance: tiktok_processing.file_sensor scheduled__2023-05-10T00:00:00+00:00 [running]> on host 49e2673af856
[2023-05-11T10:56:28.069+0000] {logging_mixin.py:149} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/sqlalchemy.py:124 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2023-05-11T10:56:47.308+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='tiktok_processing' AIRFLOW_CTX_TASK_ID='file_sensor' AIRFLOW_CTX_EXECUTION_DATE='2023-05-10T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-05-10T00:00:00+00:00'
[2023-05-11T10:56:47.446+0000] {base.py:73} INFO - Using connection ID 'fs_default' for task execution.
[2023-05-11T10:56:47.463+0000] {filesystem.py:64} INFO - Poking for file /opt/***/data/tiktok_google_play_reviews.csv
[2023-05-11T10:57:17.833+0000] {base.py:73} INFO - Using connection ID 'fs_default' for task execution.
[2023-05-11T10:57:17.834+0000] {filesystem.py:64} INFO - Poking for file /opt/***/data/tiktok_google_play_reviews.csv
[2023-05-11T10:57:17.838+0000] {filesystem.py:69} INFO - Found File /opt/***/data/tiktok_google_play_reviews.csv last modified: 20230504102257
[2023-05-11T10:57:17.839+0000] {base.py:255} INFO - Success criteria met. Exiting.
[2023-05-11T10:57:17.859+0000] {taskinstance.py:1373} INFO - Marking task as SUCCESS. dag_id=tiktok_processing, task_id=file_sensor, execution_date=20230510T000000, start_date=20230511T105603, end_date=20230511T105717
[2023-05-11T10:57:17.900+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 0
[2023-05-11T10:57:17.978+0000] {taskinstance.py:2674} INFO - 1 downstream tasks scheduled from follow-on schedule check
